version: "3.7"

volumes:
  db-data:
  pgadmin-data:

services:
  web:
    build:
      context: "."
      args:
        NODE_ENV: development
    command: "yarn dev"
    depends_on:
      - db
    ports:
      - "3001:3001"
      - "9229:9229"
      - "9230:9230"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: "true"
      PORT: 3001
      JWT_SECRET: "0xPdREWZ&wXYVWjAU0lFA9Eh@eLfn^ZVg&jcg"

  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - db-data:/var/lib/postgres/data/

  pgadmin4:
    image: dpage/pgadmin4
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=docker@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=docker
    ports:
      - 6500:80
